/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include"FreeRTOSConfig.h"
#include"FreeRTOS.h"
#include"task.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vMainLedTask1(void * pvParam)
{
	uint16_t led_pin = ((uint16_t *) pvParam)[0];
	uint16_t led_delay = ((uint16_t *) pvParam)[1];
	while(1)
	{
		// work
		led_toggle(led_pin);
		vTaskDelay(led_delay / portTICK_RATE_MS);
	}
	vTaskDelete(NULL);
}


int main(void)
{
	led_init(LED_BLUE);
	led_init(LED_RED);
	led_init(LED_GREEN);
	led_init(LED_ORANGE);

	static uint16_t blue[2]={LED_BLUE,4000};
	static uint16_t red[2]={LED_RED,3000};
	static uint16_t green[2]={LED_GREEN,2000};
	static uint16_t orange[2]={LED_ORANGE,1000};

	xTaskCreate(vMainLedTask1, "blue", configMINIMAL_STACK_SIZE, blue, 4, NULL);
	xTaskCreate(vMainLedTask1, "red", configMINIMAL_STACK_SIZE, red, 3, NULL);
	xTaskCreate(vMainLedTask1, "green", configMINIMAL_STACK_SIZE, green, 2, NULL);
	xTaskCreate(vMainLedTask1, "orange", configMINIMAL_STACK_SIZE, orange, 1, NULL);

	vTaskStartScheduler();
	while(1);
}














